import { useState } from "react";
import type { SkuHealth, Role } from "../engine/types";
import { getRecommendation } from "../ai/recommendationClient";
import { RoleSelector } from "./RoleSelector";
import { ConfidenceBadge } from "./ConfidenceBadge";
import { DataQualityFlag } from "./DataQualityFlag";

interface Props {
  health: SkuHealth;
}

export function AiRecommendationPanel({ health }: Props) {
  const [role, setRole] = useState<Role>("planner");
  const [text, setText] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>("");

  async function generate() {
    setLoading(true);
    setError("");
    setText("");
    try {
      const recommendation = await getRecommendation(health, role);
      setText(recommendation);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Request failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="ai-panel">
      <div className="ai-panel-header">
        <h4 className="panel-title">AI Recommendation</h4>
        <div className="ai-meta">
          <ConfidenceBadge level={health.confidence} reason={health.confidenceReason} />
          <span className="layer-note">Confidence computed by Layer 1 engine</span>
        </div>
      </div>

      <DataQualityFlag quality={health.dataQuality} reason={health.confidenceReason} />

      <div className="ai-controls">
        <RoleSelector role={role} onChange={setRole} />
        <button
          className="btn-generate"
          onClick={generate}
          disabled={loading}
        >
          {loading ? "Generating…" : "Generate recommendation"}
        </button>
      </div>

      {error && <div className="ai-error">{error}</div>}

      {text && (
        <div className="ai-output">
          <div className="ai-role-label">Role: {role}</div>
          <p>{text}</p>
          <div className="ai-disclaimer">
            Generated by LLM (Groq / Llama 3.3 70B) · Numbers sourced from Layer 1 engine only
          </div>
        </div>
      )}
    </div>
  );
}
