import { useRef, useState } from "react";
import type { SkuHealth, Role } from "../engine/types";
import { getRecommendation } from "../ai/recommendationClient";
import type { RecommendationResult } from "../ai/recommendationClient";
import { RoleSelector } from "./RoleSelector";
import { ConfidenceBadge } from "./ConfidenceBadge";
import { DataQualityFlag } from "./DataQualityFlag";

interface Props {
  health: SkuHealth;
}

const ERROR_MESSAGE =
  "Failed to get recommendation. Check that the API server is running (npm run dev:api).";

export function AiRecommendationPanel({ health }: Props) {
  const [role, setRole] = useState<Role>("planner");
  const [result, setResult] = useState<RecommendationResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>("");
  // Guards against a slow in-flight request overwriting state after the user
  // has switched role or fired a newer request.
  const requestId = useRef(0);

  function handleRoleChange(next: Role) {
    if (next === role) return;
    setRole(next);
    // A recommendation is role-specific, so clear it — the user must regenerate.
    setResult(null);
    setError("");
    requestId.current++;
  }

  async function generate() {
    const id = ++requestId.current;
    setLoading(true);
    setError("");
    setResult(null);
    try {
      const res = await getRecommendation(health, role);
      if (id === requestId.current) setResult(res);
    } catch {
      if (id === requestId.current) setError(ERROR_MESSAGE);
    } finally {
      if (id === requestId.current) setLoading(false);
    }
  }

  return (
    <div className="ai-panel">
      <div className="ai-panel-header">
        <h4 className="panel-title">AI Recommendation</h4>
        <div className="ai-meta">
          <ConfidenceBadge confidence={health.confidence} />
          <span className="layer-note">Confidence computed by Layer 1 engine</span>
        </div>
      </div>

      <DataQualityFlag dataQuality={health.dataQuality} reason={health.confidenceReason} />

      <RoleSelector role={role} onChange={handleRoleChange} />

      <button className="btn-generate btn-block" onClick={generate} disabled={loading}>
        {loading ? "Generating…" : "Generate recommendation"}
      </button>

      {loading && (
        <div className="ai-loading">
          <span className="spinner" aria-hidden="true" /> Generating recommendation…
        </div>
      )}

      {error && (
        <div className="ai-error">
          <span className="ai-error-msg">{error}</span>
          <button className="ai-retry-btn" onClick={generate}>Retry</button>
        </div>
      )}

      {result && !loading && (
        <div className="ai-output">
          <div className="ai-role-label">Role: {role}</div>
          <p>{result.recommendation}</p>
          {result.grounded ? (
            <div className="ai-grounding-ok">✓ All figures grounded in Layer 1 data.</div>
          ) : (
            <div className="ai-grounding-warn">
              ⚠ Ungrounded figure detected — verify against engine values.
            </div>
          )}
          <div className="ai-disclaimer">
            Generated by Llama 3.3 70B via Groq · Grounded in Layer 1 data
          </div>
        </div>
      )}
    </div>
  );
}
