import { useRef, useState } from "react";
import type { SkuHealth } from "../engine/types";
import { getPortfolioBrief } from "../ai/briefClient";

interface Props {
  items: SkuHealth[];
}

const ERROR_MESSAGE =
  "Failed to generate briefing. Check that the API server is running (npm run dev:api).";

export function PortfolioBrief({ items }: Props) {
  const [brief, setBrief] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>("");
  // Guards against a slow in-flight request overwriting state after a newer one fires
  // (e.g. the user changed the store filter and regenerated).
  const requestId = useRef(0);

  async function generate() {
    const id = ++requestId.current;
    setLoading(true);
    setError("");
    setBrief("");
    try {
      const text = await getPortfolioBrief(items);
      if (id === requestId.current) setBrief(text);
    } catch {
      if (id === requestId.current) setError(ERROR_MESSAGE);
    } finally {
      if (id === requestId.current) setLoading(false);
    }
  }

  return (
    <div className="ai-panel">
      <div className="ai-panel-header">
        <h4 className="panel-title">AI Planner Briefing</h4>
        <span className="layer-note">Set-level summary · grounded in Layer 1 data</span>
      </div>

      <button
        className="btn-generate btn-block"
        onClick={generate}
        disabled={loading || items.length === 0}
      >
        {loading ? "Generating…" : "Generate briefing"}
      </button>

      {loading && (
        <div className="ai-loading">
          <span className="spinner" aria-hidden="true" /> Generating briefing…
        </div>
      )}

      {error && (
        <div className="ai-error">
          <span className="ai-error-msg">{error}</span>
          <button className="ai-retry-btn" onClick={generate}>Retry</button>
        </div>
      )}

      {brief && !loading && (
        <div className="ai-output">
          <p>{brief}</p>
          <div className="ai-disclaimer">
            Generated by Llama 3.3 70B via Groq · Grounded in Layer 1 data
          </div>
        </div>
      )}
    </div>
  );
}
